### ISSUE TITLE
Stone Placing Sound on Right Click in Dev Space

### ISSUE THREAD

**Issue by RedVortexDev** [DFOnline/CodeClient#11]
Right-clicking anything in the dev space causes a stone place sound

**Comment by GeorgeRNG** [comment]
This is because of the system to reimplement block placing sounds, it triggers without a block place and defaults to stone because of items

**Comment by RedVortexDev** [comment]
Why are you replacing/messing with sounds again?

**Comment by GeorgeRNG** [comment]
I'm messing with placing, and it then messes with sounds
