### ISSUE TITLE
On node beta tag switching happens twice

### ISSUE THREAD

**Issue by RedVortexDev** [DFOnline/CodeClient#15]
https://github.com/DFOnline/CodeClient/assets/58099979/94f2d26f-5f4e-48e9-a821-5b451f371d00

Im really not sure whats going on, only happens in beta

**Comment by GeorgeRNG** [comment]
Disable **Custom Tag Interaction** in the config

**Comment by GeorgeRNG** [comment]
I will be disabling Custom Tag Interaction for now
