### ISSUE TITLE
Can't type while doing /getactiondump

### ISSUE THREAD

**Issue by sbot50** [DFOnline/CodeClient#27]
if its downloading/if you didnt do /abort at the end you get kicked for "invalid signature"

edit: /getactiondump is completely borked atm

**Comment by GeorgeRNG** [comment]
I don't have experience of this myself, however getactiondump does block all packets, and might mess with recode.
I only recommened use of getactiondump without any other mods and in IntelliJ, since that's when I run it, it works fully such as this and encoding errors.
