### ISSUE TITLE
Cannot place codeblocks which are items

### ISSUE THREAD

**Issue by GeorgeRNG** [DFOnline/CodeClient#28]
Get a codeblock which icon is an item, try and place it.

**Comment by sbot50** [comment]
I would like to add that it worked previously but you broke it, the system was that if its an item and not a block it switches it into a block then places it and then switches it back to what it previously was, why/how you borked it i have no clue

**Comment by GeorgeRNG** [comment]
I changed the system, I no longer have code which runs after I send the interaction packet.
I think it was https://github.com/DFOnline/CodeClient/commit/d6706c3687fa2eff47adca7a130cfd688cc836e8
