### ISSUE TITLE
Second Chat

### ISSUE THREAD

**Issue by sbot50** [DFOnline/CodeClient#37]
Add recode's second chat feature, including:
1. A second chat
2. A custom filter for words/phrases you can put into second chat
3. /msg
4. Supper chat
5. Session spy chat
6. Mod chat
7. Admin chat

And for all those have the option to
1. add a sound to them
2. select which chat they should go to
3. (recode doesnt have this but would be cool) a toggle to make them highlighted in chat

Having options to resize the chat or move it to a different place would be cool too
Maybe having more than 2 chats would also be possible but i wouldnt see any use for that.

**Comment by RedVortexDev** [comment]
why not use recode's? codeclient is supposed to be kinda like more coding focused and if recode has the exact same features as this issue does, and works perfectly, why go through the trouble to add it to codeclient?

**Comment by GeorgeRNG** [comment]
![image](https://github.com/DFOnline/CodeClient/assets/81434111/62e3db6b-9ceb-4c35-bb09-578ae2b3a8ee)

**Comment by GeorgeRNG** [comment]
anyway this is difficult to implement, so I don't really want to implement it.

**Comment by RedVortexDev** [comment]
sidechat is not the reason people use recode, if that was the reason people would have used lessutilties instead (does have sidechat)
