### ISSUE TITLE
Sodium Incompatablity 

### ISSUE THREAD

**Issue by GeorgeRNG** [DFOnline/CodeClient#41]
~~A mod in FO~~ sodium modifies chunk rendering which disables the block render modification at https://github.com/DFOnline/CodeClient/blob/v86/src/main/java/dev/dfonline/codeclient/mixin/render/MChunkRendererRegion.java

**Comment by GeorgeRNG** [comment]
Automatic plot sizing is also in this, so that also breaks.

**Comment by RedVortexDev** [comment]
Fabulously Optimized is just a modpack so it has nothing to do with this

**Comment by RedVortexDev** [comment]
The actual affecting mod should be searched

**Comment by GeorgeRNG** [comment]
I don't know which mod, it's just one in FO

**Comment by sbot50** [comment]
The issue is sodium

**Comment by RedVortexDev** [comment]
I think you added the label to the wrong issue :)

**Comment by GeorgeRNG** [comment]
Fixed automatic plot sizing. Might drop the hiding. I can't find a point before sodium which I can mixin to any get block.

**Comment by GeorgeRNG** [comment]
stale and all incompatible features are gone
