### ISSUE TITLE
Temporary chest highlight on quick inserted items

### ISSUE THREAD

**Issue by RedVortexDev** [DFOnline/CodeClient#50]
### Why?
Many time when I left click on a chest with a value or a variable I hear the plop sound but the item is not there,
sometimes DF just doesn't put the item, and some times I missclick and put it in another chest, a chest which I am unable to find 90% of the time

**Comment by GeorgeRNG** [comment]
i read this as making items highlight when added recently added in a chest lmao but this is good.
(idk how to make blocks glow, recode code dive time)
