### ISSUE TITLE
Preview Chest Contents text display is inside chests.

### ISSUE THREAD

**Issue by FlyingPig525** [DFOnline/CodeClient#54]
## Why is this an issue?
It causes me to not be able to read what the text displays say, therefore nullifying the point of the preview.

## Proposed fix
Either move the text display out of the center of the chest, or make it show over all blocks.

## Image of issue
![image](https://github.com/DFOnline/CodeClient/assets/66709612/1386d8db-eeec-4ed8-9060-53ecfce42efe)

**Comment by FlyingPig525** [comment]
Quick note, this only happens on my computer. When I use the mod on my phone, using pojav launcher, it displays over the chest. I have no idea why this is happening.

**Comment by FlyingPig525** [comment]
With further testing, this seems to be an issue with having Enhanced Block Entities in my mods folder, sad :((((((((((

**Comment by GeorgeRNG** [comment]
it is supposed to show over all blocks. Perhaps EBE is making chests render in the same other transparent blocks like glass do, which also cover my overlay. The solution would be to put it on the screen, or find a better method on putting everything on top
