### ISSUE TITLE
[Bug] Custom block breaking prevents the glitch stick from functioning.

### ISSUE THREAD

**Issue by Totobird-Creations** [DFOnline/CodeClient#55]
**Context**
DF has a feature called the "glitch stick". If you know what it is, skip to the next section.
It is obtained using the command `/p g`, and can break pieces of blocks. For example, you can use it to break either the opening bracket or the closing bracket, in order to move something into or out of an if statement.

**Problem**
Enabling the "custom block breaking" setting breaks the glitch stick, preventing it from functioning.

**Potential Solution**
The nbt of the glitch stick includes `{ PublicBukkitValues : { "hypercube:item_instance" : "15b8bde4-f6cc-4bb8-bbf0-6b747db2f753" } }`. When left clicking a block, check if the mainhand item has that nbt tag. If so, act like custom block breaking functionality is disabled for the current break attempt, using the vanilla system instead.

**Attachments**
Below is a video of the uses of the glitch stick, when "custom block breaking" is disabled.

https://github.com/DFOnline/CodeClient/assets/45902300/9be146b6-bd13-4701-b54c-761abfaf75fa

**Comment by GeorgeRNG** [comment]
This should've been fixed in https://github.com/DFOnline/CodeClient/commit/4168f2a850ccb89dc489198e2159285e0e883122
[Update](https://github.com/DFOnline/CodeClient/releases/tag/v110) and see if the issue persists.

**Comment by Totobird-Creations** [comment]
That works. It just wasn't on Modrinth yet. Thank you.

**Comment by GeorgeRNG** [comment]
tmk item_instance is per-node
