### ISSUE TITLE
code blocks being moved around in inventory when trying to place on codelines

### ISSUE THREAD

**Issue by blikthepro** [DFOnline/CodeClient#60]
following video describes this bug the best
https://github.com/DFOnline/CodeClient/assets/89069658/fc8eab73-9fd6-4ffc-859e-61e8ce25e714

it could be a result of one in many of the client side mods i have installed conflicting with codeclient. i have tried disabling all the options in the mod's settings, restarting, as well as reinstalling, with no results

**Comment by GeorgeRNG** [comment]
can you send logs if they seem relevant or a list of your other mods, and removing codeclient resolves the issue?

**Comment by GeorgeRNG** [comment]
closing as stale
