### ISSUE TITLE
flight anywhere with phaser

### ISSUE THREAD

**Issue by JayRPlayz** [DFOnline/CodeClient#64]
**basicly Flight anywhere with code client**

Reproduction:
1. enable noclip in dev in the config
2. go in dev and fall into the void, like really far down
3. join anywhere that is in the same node. if using 1.20.1 or lower (can be done with via fabric plus) it will work cross node
4. do something for that you dont have the permissions for (/dev or /build) as long as you dont have permission for that command, you will get teleported the that plot.
5. double tap space to start flying

Expected Result:
instantanious teleport to the plot

Actual Result:
staying there, where you were, and falling throu the ground, if there is ground

**Comment by GeorgeRNG** [comment]
the buildspace phaser which is default V? if it is that one, how do you leave or join a plot whilst holding V
Or is it the regular noclip breaking?
Also, try running /fixcc while in the broken state

**Comment by JayRPlayz** [comment]
update, it still works in ver 1.5.7

**Comment by GeorgeRNG** [comment]
I can't recreate it my version, and 1.5.7 isn't supported, we're on 1.5.9.
Please recreate it in the latest version, and provide a video because I have no idea what you're doing.

**Comment by JayRPlayz** [comment]
ok

**Comment by JayRPlayz** [comment]
just tested it in newest version, it still works.

just use phaser on any plot, then do /spawn and try to fly

it doesnt work across nodes anymore, minecraft update 1.20.2 fixed it across nodes

**Comment by GeorgeRNG** [comment]
i fixed a flight issue at spawn but some of the other behaviour I don't understand so I'm closing this as stale
