### ISSUE TITLE
NBT Editor crashed when tooltips are displayed outside of a menu

### ISSUE THREAD

**Issue by JayRPlayz** [DFOnline/CodeClient#65]
every time i try to go in dev 

i dont know the cause :(

- [X] I am using the [latest version](https://github.com/DFOnline/CodeClient/releases).
- [X] I have tried disabling various options to see if they cause the issue, such as new ones or ones I have recently enabled.
- sodium isnt the problem

**Comment by GeorgeRNG** [comment]
please upload crash logs

**Comment by JayRPlayz** [comment]
[rei.log](https://github.com/DFOnline/CodeClient/files/13623849/rei.log)
[rei-issues.log](https://github.com/DFOnline/CodeClient/files/13623850/rei-issues.log)
[latest.log](https://github.com/DFOnline/CodeClient/files/13623851/latest.log)
here are the three logs, btw i think its caused by "roughly enough items"

**Comment by JayRPlayz** [comment]
nvm, rei isnt the problem
[rei-issues.log](https://github.com/DFOnline/CodeClient/files/13623904/rei-issues.log)
[latest.log](https://github.com/DFOnline/CodeClient/files/13623905/latest.log)
[rei.log](https://github.com/DFOnline/CodeClient/files/13623903/rei.log)

**Comment by GeorgeRNG** [comment]
Does the issue stop happening when you uninstall nbteditor?

**Comment by JayRPlayz** [comment]
it doesnt crash without nbt editor, is there a fix? because i really want to use nbt editor, and the previous versions work with nbt editor, but dont work with IBE editor

**Comment by GeorgeRNG** [comment]
Okay, I've identified the issue. nbt editor doesn't like tooltips (from chest peeker, seeing signs which are too long and signs from behind) outside of screens.
It's an NBT Editor issue at https://github.com/mega12345mega/NBT-Editor/issues/56
However, as mega12345mega says:
> In the meantime, I believe if you disable "Tooltip Overflow Fix" in the /nbt config screen, the crash should stop. The disadvantage is that this will make images imported as item lore basically impossible to view if they are not at a tiny resolution.

**Comment by JayRPlayz** [comment]
ok, thx!

**Comment by JayRPlayz** [comment]
i dont need tooltip overflow fix anyway

**Comment by mega12345mega** [comment]
I've now fixed this in v1.13.0, so I think this can be closed. Sorry for the inconvenience! (Technically I only tested with the EssentialsGUI mod mentioned in the issue on my repo, so you might want to check just to be sure.)

**Comment by GeorgeRNG** [comment]
tyvm, I'll testing that on our mod then

**Comment by RedVortexDev** [comment]
As mentioned in the NBT Editor issue, this has been resolved in v1.13.0. This issue can be closed.
