### ISSUE TITLE
minecraft refuses to start with codeclient 1.5.7

### ISSUE THREAD

**Issue by JayRPlayz** [DFOnline/CodeClient#68]
my minecraft just doesnt start, when codeclient 1.5.7 is installed, even when theres only "yet another config lib" and "codeclient" installed.

**Expected behavior**
The game is supposed to start, what else?

cant make screeenshots of a non starting game.

- [ ] I am using the [latest version](https://github.com/DFOnline/CodeClient/releases).
- [X] I have tried disabling various options to see if they cause the issue, such as new ones or ones I have recently enabled.
- [X] I cant use the version 1.5.7 because of this bug

**Comment by JayRPlayz** [comment]
if its possible bring out a version of codeclient for 1.20.1 with this issue fixed. i still use 1.20.1 bc its more stable

**Comment by GeorgeRNG** [comment]
> if its possible bring out a version of codeclient for 1.20.1 with this issue fixed. i still use 1.20.1 bc its more stable

The latest non 1.20.2 version is https://github.com/DFOnline/CodeClient/releases/tag/v126
If you can't screenshot you can provide logs
