### ISSUE TITLE
Support for new underground codespace on node beta

### ISSUE THREAD

**Issue by AlignedCookie88** [DFOnline/CodeClient#69]
**Describe the feature you'd like**
Add support for node beta's new underground codespace (created using `/p codespace underground create`).

**Has it already been considered?**
I've checked the existing issues. No other issues exist.

**Does it fit CodeClient**
- [x] Does it not affect gameplay, or anything outside DiamondFire?
- [x] Is it not in recode?

**Comment by GeorgeRNG** [comment]
This has been done, but it isn't assigned as latest because it's for beta: https://github.com/DFOnline/CodeClient/releases/tag/v149
I would also personally categorize this in a Bug Report.
