### ISSUE TITLE
CCDBUG kicks me with Internal Exception: java.lang.NullPointerException: Cannot assign field "type" because "dev.dfonline.codeclient.dev.Debug.Debug.variable" is null

### ISSUE THREAD

**Issue by AlignedCookie88** [DFOnline/CodeClient#70]
**Describe the bug**
I was trying to setup CCDBUG for the first time and stumbled upon this. Using CCDBUG seems to throw the following error:
> Internal Exception: java.lang.NullPointerException: Cannot assign field "type" because "dev.dfonline.codeclient.dev.Debug.Debug.variable" is null
The log isn't going into any more detail (no stacktrace for some reason) so I don't see any point in sharing it.

**To Reproduce**
1. Enable CCDBUG
2. Copy the setup from my screenshots.
3. /play

**Expected behavior**
I expected it to display debug text on the screen.

**Screenshots**
![2024-04-01_00 16 03](https://github.com/DFOnline/CodeClient/assets/52969840/1f92d654-9e8d-4d9c-9e9a-8e037cdd357b)
![2024-04-01_00 16 05](https://github.com/DFOnline/CodeClient/assets/52969840/cb63a2e0-3863-4772-bea0-9523d781766c)
![2024-04-01_00 16 07](https://github.com/DFOnline/CodeClient/assets/52969840/1a375722-8520-4622-a108-73083f063f4a)
![2024-04-01_00 16 10](https://github.com/DFOnline/CodeClient/assets/52969840/6785335a-be64-4d2f-ba0b-d7d6cb061022)
![2024-04-01_00 23 53](https://github.com/DFOnline/CodeClient/assets/52969840/0ee2e40f-bc58-4f95-9a3c-f80574837826)

**Checks**
Please check all these for more infomation with the bug.
- [x] I am using the [latest version](https://github.com/DFOnline/CodeClient/releases). *I downloaded the one from modrinth, not sure if that makes a difference)*
- [ ] I have tried disabling various options to see if they cause the issue, such as new ones or ones I have recently enabled.

**Comment by GeorgeRNG** [comment]
Forgot to close this, I changed how CCDBUG works: https://github.com/DFOnline/CodeClient/commit/08050f03f1562130deb183ac474cc289316ce3ed
Using it should be far simpler, but it means all data needs to be handled plot side: https://github.com/DFOnline/CodeClient/wiki/ccdbug
